FROM maven:amazoncorretto

USER root
WORKDIR /app/java

COPY . .
COPY order-service ./



RUN  mvn package

RUN ls -ltR

ENTRYPOINT ["/bin/sh", "-c", "java -jar /app/java/target/order-service-0.0.1-SNAPSHOT.jar"]
