FROM maven:amazoncorretto

USER root
WORKDIR /app/java

COPY . .
COPY order-service ./
RUN ls -ltr


RUN  mvn package

RUN ls -ltR

CMD [ "java", "-jar", "/app/java/target/order-service-0.0.1-SNAPSHOT.jar"]
