FROM maven:amazoncorretto

USER root
WORKDIR /app/java

COPY . .
COPY order-service ./
RUN ls -ltr


RUN  mvn package
RUN pwd
RUN ls -ltR

ENTRYPOINT [ "java", "-jar", "/target/order-service-0.0.1-SNAPSHOT.jar"]
